# Generated by Django 4.1.1 on 2022-10-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='hall',
            new_name='gallery',
        ),
    ]
